[project]
name = "o-phone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.11.9",
    "python-dotenv>=1.2.1",
]
